#run1.mac
#Creacion de fuente cuadrada plana mono-energetica
/control/verbose 0
/tracking/verbose 2
#
/run/initialize
#Direccion y tipo de fuente
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 0. 0. -12.0 mm
# 
#
/gps/pos/halfx 1.0 mm
/gps/pos/halfy 6.0 mm
#
#
/gps/particle proton
/gps/direction 0. 0. 1.
#
#
#
/gps/energy 5.25 MeV
# 
###/control/execute vis.mac
#
/run/printProgress 10000
#
/run/beamOn 1000
